### ISSUE TITLE
Implement REST methods for usages

### ISSUE THREAD

**Issue by csjx** [DataONEorg/bookkeeper#13]
We manage usages through the `UsagesResource` (and the `QuotasResource`), and need to finish the implementation of:

- [ ] `QuotaList` = `listQuotas()`:   `GET     /quotas?subscribers=:subscribers&quotaType=:quotaType&requestor=:requestor`
- [ ] `Usage`     = `createUsage()`:  `POST    /usages`
- [ ] `Usage`     = `updateUsage()`:  `PUT     /usages/:id`
- [ ] `boolean`  = `deleteUsage(`):  `DELETE  /usages/:id`

The administrative listing of usages can come in a later release, but I'll list it here too:
`UsageList`      = `listUsage()`:    `GET     /usages?quotaType=:quotaType&instanceId=:instanceId&subscribers=:subscribers`

**Comment by csjx** [comment]
Yup, see https://github.com/DataONEorg/bookkeeper/issues/14 - let's add the constraint on the two columns.

**Comment by gothub** [comment]
The `/usages` REST methods were implemented in commit fcb22b0f2b2471565816f300b3d4d96317b07a00
