### ISSUE TITLE
Change database schema and models for managing quotas and usages 

### ISSUE THREAD

**Issue by csjx** [DataONEorg/bookkeeper#14]
We need to know which repository is related to a given `Usage` of a `Quota`:

- [x] Change the model and add a `nodeId` attribute.  
- [x] Change the `quotas` table and add a uniqueness constraint for the `subscriptionId` and `quotaName` field combinations so we only have one row for a given quota type associated with a given subscription.  
- [x] Change the `Quota.name` field to `Quota.quotaType` and reflect it in the schema, classes, and tests.

**Comment by gothub** [comment]
The `nodeId` will be in the usages model only.

**Comment by gothub** [comment]
Completed in commits 33f41cfac71545bc770ff544c8d091dd75205fb0 and 40e482b6cb0cca623ec7250f5a26cac1faa1dd47
