### ISSUE TITLE
Deploy bookkeeper to the testing cluster

### ISSUE THREAD

**Issue by csjx** [DataONEorg/bookkeeper#16]
Deploy containerized versions of 
1) Postgres with the bookkeeper schema and 
2) The bookkeeper application on the development Kubernetes cluster.

**Comment by gothub** [comment]
This task will include this metadig-engine [issue](https://github.com/NCEAS/metadig-engine/issues/240), which describes the k8s bookkeeper role and ingress

**Comment by gothub** [comment]
What data is needed for this test deployment, i.e. "customers", "subscriptions", "quotas", etc.

**Comment by gothub** [comment]
bookkeeper has been deployed on dev k8s and is available at https://docker-dev-ucsb-1.test.dataone.org:30443/bookkeeper. Once an LetsEncrypt cert issue is resolved, it will be available from https://api.test.dataone.org/bookkeeper.

Four test customers are in the bookkeeper database as described [here](https://hpad.dataone.org/bsqdI-gpSjutJKWqUnpuhw?view), under "2020 06 30".
