### ISSUE TITLE
The delete usage method doesn't return a boolean result

### ISSUE THREAD

**Issue by taojing2002** [DataONEorg/bookkeeper#49]
In our design document, the delete usage method should return a boolean result. However, it return a blank string.

**Comment by gothub** [comment]
@taojing2002 the delete usage service returns an HTTP status of 200 if the request is successful, or an error status if it isn't
successful. Is that sufficient?

**Comment by taojing2002** [comment]
@gothub To me, it is fine. I just concern it doesn't match our design document -
```
boolean   = deleteUsage():  DELETE  /usage/:id
```
If we all have an agreement that  we don't need to return the boolean, it is totally fine to me.

**Comment by gothub** [comment]
@taojing2002
The bookkeeper `delete` methods for all resources ("customers", "products", ...) all return HTTP 200 on success, so I'd say let's go with that.

I just opened an issue for creating a Swagger definition for the bookkeeper API. When this is created, this should be the reference for the bookkeeper API.
