### ISSUE TITLE
Rename Quota.usage to Quota.totalUsage

### ISSUE THREAD

**Issue by csjx** [DataONEorg/bookkeeper#53]
Discussing this, `usage` was confusing because of the `usages` collection, so rename this `totalUsage`.

**Comment by csjx** [comment]
Also, when refactoring `Quota.getUsage()` to `Quota.getTotalUsage()`, initialize the result to `0` and if there is a `null` result, return `0` instead.  This makes downstream processing easier.

**Comment by gothub** [comment]
Fixed in commits:
- da5121a7fa736c3fa3063429b8d0b0ddce4b5b0b
- 019001185ee0704a857e4c3cf89e0d8398184772
