### ISSUE TITLE
Change 'quota.subject' to 'quota.subscriber' in database and models

### ISSUE THREAD

**Issue by gothub** [DataONEorg/bookkeeper#54]
@csjx for an earlier issue, 'quota.name' was changed to 'quota.quotaType'. That would have been a good time
to also update 'subject' to 'subscriber', but that didn't get done. The user facing instances of 'subject' have been changed to 'subscriber'. Should the internal instances of 'subject' be changed?

**Comment by csjx** [comment]
Yes, I think they should too.  It will keep the confusion down in years to come.

**Comment by gothub** [comment]
Fixed in commits 
- d2aea0df24eae739f615e55f1d236c3953da24b0 
- a63d885126a518e6b5919144c16dbf8dbc67c18c
