### ISSUE TITLE
Add a UsagesResource.getUsageStatus API endpoint

### ISSUE THREAD

**Issue by csjx** [DataONEorg/bookkeeper#55]
After discussion, we realized that we need a non-authenticated API endpoint that allows public users to find out whether a given portal's usage (by its `instanceId` and `quotaType`) is active.  This allows us to conditionally render paid features for the portal.

- [x] Add the `GET /usages/status?instanceId=:instanceId&quotaType=:quotaType` method to the Swagger API
- [x] Create a `UsageStatus` model with one `status` property with values of `active` or `inactive`:
```json
{
    "status": ":status"
}
```
> Note: Should the `UsageStatus` model also include the `"object": "usagestatus"` field to be consistent with our other models?
- [x] Modify `UsagesResource` and add the `getStatus()` method (leave out the `@PermitAll` annotation) which returns a `UsageStatus` model in `200` responses, otherwise `404` if not found.
- [x] Write up a `UsageTest` serialization/deserialization unit test for the model using a `usagestatus.json` fixture

**Comment by gothub** [comment]
Added in these commits:
- a9f20c1daa857521a58bedcc908f2c57239a6ebf
- 5ba6aa7814ac12925daf0e2b9bce689dab306eb4
- a488674a4a489219b754c1c874b7d29e8d6de3b8
- 50a8dabf7f0980562b56ce58d7cc32a478edaf17
