### ISSUE TITLE
Usages table constraint

### ISSUE THREAD

**Issue by gothub** [DataONEorg/bookkeeper#7]
@csjx In the usages table it is possible to create multiple entries for the same storage, for example

```
   id | object  | quotaid |                  instanceid                   | quantity | status
  ----+---------+---------+-----------------------------------------------+----------+--------
  5 | storage |       1 | urn:urn:6B444FC1-6CAF-45A4-BC5B-8BD27A6D9B48  |    22220 | active
  6 | storage |       1 | urn:urn:6B444FC1-6CAF-45A4-BC5B-8BD27A6D9B48  |    22220 | active
  7 | storage |       1 | urn:urn:6B444FC1-6CAF-45A4-BC5B-8BD27A6D9B48  |    22220 | active
```
The `instanceid` column is indexed, but does not have a `UNIQUE` constraint.

Should a `UNIQUE` constraint be added to this column, or alternatively, should the constraint be multi-column, on 'object,instanceid'?

**Comment by csjx** [comment]
@gothub, I think we need a `UNIQUE` constraint on `instanceId`.  This is the classic upsert issue that we need to deal with in the code.

Also, the value of the `object` column in the `usages` table should always be `usage`.  The `quotas.quotaType` (previously `quotas.name`) stores the type of the quota, and is linked in the `usages` table by `quotaId`.  The `object` column is merely an artifact of translating from JSON objects to SQL tables.  Each of the bookkeeper models have an `object` property, like:

```json
{
    "id": 54321,
    "object": "usage",
    "quotaId": 1,
    "instanceId": "urn:uuid:56925d4b-9e46-49ec-96ea-38dc9ed0a64c",
    "quantity": 1099511627776.0,
    "nodeId": "urn:node:KNB",
    "status": "active"
}
```

**Comment by gothub** [comment]
@csjx ok, well that makes sense from a db consistency standpoint that the same info (usage type) shouldn't be duplicated in multiple tables. 

If every row of the `usages` table is going to have the same value for the `object` column, then why are we including in in the `usage` JSON? Is this to identify that this is a `usage` object? If so, wouldn't that be assumed from the context of the REST request that is sending or retrieving this object?

**Comment by gothub** [comment]
In the 06/12/2020 dev call, @taojing2002 mentioned that the unique constraint should be on
quotaId + instanceId, as both of there may be multiple rows for either one of these columns individually, but the combination of the two should be unique.

Note that from the client's point of view, quotaType + instanceId is a more logical choice, however, the usages table does not contain quotaType (that is only in the quota table). The quotaId column is therefor used instead. 

A quotaId parameter must also be added to the `usages` endpoint, which will be described in a different issue.

**Comment by gothub** [comment]
Set a UNIQUE constraint on usages table for `quotaid + instanceid` in commit 681bc214ef074864c00305b2699758f7309a7db8
