### ISSUE TITLE
listOrders() returns http 500 status

### ISSUE THREAD

**Issue by gothub** [DataONEorg/bookkeeper#70]
Listing orders with GET `/bookkeeper/v1/orders' causes http 500 status to be returned, with the terse error msg:
```
{"code":500,"message":"Couldn't list orders: null"}
```

**Comment by gothub** [comment]
@csjx This error occurred at line https://github.com/DataONEorg/bookkeeper/blob/master/src/main/java/org/dataone/bookkeeper/resources/OrdersResource.java#L148 which should be changed to
```
            } else if ( subject != null && ! subject.isEmpty() ) {
```

However, `listOrders` needs to be refactored, as the following need to be provided:
- needs to return http 404 if order is not found when either `subject` or `customerId` is specified
  - currently returns empty order object
- needs to return http 403 if user isn't an admin user
  - currently returns empty order object

**Comment by gothub** [comment]
@csjx also, `listOrders` currently has the `subject` param, but does not have the `requestor` param that is documented at https://app.swaggerhub.com/apis/dataoneorg/bookkeeper/v1#/Orders/listOrders

**Comment by csjx** [comment]
This is fixed.  We had a null pointer exception in the call. I also refactored the `pay()` logic and the `listOrders()` logic to address the points above.
