### ISSUE TITLE
Usages table `status` column

### ISSUE THREAD

**Issue by gothub** [DataONEorg/bookkeeper#8]
@csjx The `status` column in the `usages` table can be set or modified by either a `create()` or an `update()`. 

Should the setting of the `status` column be added to the `update_quota_usage_on_insert_or_update` trigger, so that on update or create `status` column of the`subscriptions` table is checked and `status` is set accordingly?

Alternatively, all `create()` calls might always set status to `active`, and update will never modify the `status` value.

**Comment by csjx** [comment]
Setting the `status` to `archived` at any point will be a manual, administrative task (hopefully rare. So We should default it to `active` in the `create()` call, yes.

**Comment by gothub** [comment]
Updated `create()` to set status to `active` in commit bcd62aaced7de9eab6513a46d973d6a0757612c1
